name = "blazenote-frontend"
compatibility_date = "2025-10-21"
compatibility_flags = ["nodejs_compat"]

[assets]
not_found_handling = "single-page-application"

[observability.logs]
enabled = true

# Custom domain configuration
[[routes]]
pattern = "blazenote-frontend.cf-testing.com"
custom_domain = true